[project]
name = "erpnext-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests",
    "mcp[cli]>=1.10.1",
    "python-dotenv>=1.0.0",
    "httpx>=0.27.0",
    "markdownify",
    "readabilipy"
]
